package main

import (
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// The generators are pinned by the proto companion image, not by anything this
// repository installs: `codefly generate proto` runs buf inside
// ghcr.io/codefly-dev/proto, whose tag fixes every plugin. These constants
// record the versions the committed stubs were produced under, so they are
// readable without decoding the generated output that is supposed to match
// them.
const (
	companionImage         = "ghcr.io/codefly-dev/proto:0.0.16"
	protocGenGoVersion     = "v1.36.11"
	protocGenGoGRPCVersion = "v1.6.1"
)

// generatedBanner matches the `// versions:` block both generators emit. They
// disagree on the separator — protoc-gen-go indents with a tab, protoc-gen-go-grpc
// uses "- " — so the plugin name anchors the match instead.
func generatedBanner(plugin string) *regexp.Regexp {
	return regexp.MustCompile(`(?m)^//\s*-?\s*` + regexp.QuoteMeta(plugin) + `\s+(v[0-9]+\.[0-9]+\.[0-9]+)`)
}

// TestGeneratedStubsMatchPinnedGenerators fails when the checked-in stubs carry
// a generator version other than the companion's. Regenerating on a host PATH
// produces exactly this diff — a one-line banner change per file that reads as
// harmless — and CI runs no buf, so nothing else would catch it.
func TestGeneratedStubsMatchPinnedGenerators(t *testing.T) {
	for _, tc := range []struct {
		file    string
		plugin  string
		version string
	}{
		{"gen/codefly/warehouse/v0/warehouse.pb.go", "protoc-gen-go", protocGenGoVersion},
		{"gen/codefly/warehouse/v0/warehouse_grpc.pb.go", "protoc-gen-go-grpc", protocGenGoGRPCVersion},
	} {
		content, err := os.ReadFile(filepath.Join(repoRoot, tc.file))
		if err != nil {
			t.Fatal(err)
		}
		match := generatedBanner(tc.plugin).FindSubmatch(content)
		if match == nil {
			t.Fatalf("%s: no %s version banner", tc.file, tc.plugin)
		}
		if got := string(match[1]); got != tc.version {
			t.Errorf("%s: generated by %s %s, but %s pins %s\n"+
				"regenerate with `codefly generate proto --proto ./proto --output ./gen`",
				tc.file, tc.plugin, got, companionImage, tc.version)
		}
	}
}

// TestBufConfigLivesWithTheProtos gates the location the companion requires:
// it mounts the tree, sets the working directory to --proto, and fails outright
// if buf.gen.yaml is not there. A config at the repository root is reachable
// only by running buf on the host, which is the unpinned path.
func TestBufConfigLivesWithTheProtos(t *testing.T) {
	for _, name := range []string{"buf.yaml", "buf.gen.yaml"} {
		if _, err := os.Stat(filepath.Join(repoRoot, "proto", name)); err != nil {
			t.Errorf("proto/%s must exist: %v", name, err)
		}
		if _, err := os.Stat(filepath.Join(repoRoot, name)); err == nil {
			t.Errorf("%s at the repository root invites host-side generation; it belongs in proto/", name)
		}
	}
}
